# Generated by Django 5.1.4 on 2025-01-13 12:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Contenido"),
        ),
    ]
